In [1]:
import tensorflow as tf

In [3]:
print(tf.__version__)

2.1.0


In [4]:
string = tf.Variable("This is a string", tf.string)
n = tf.Variable(32.0, tf.int16)
m = tf.Variable(3.567, tf.float64)

In [8]:
string

<tf.Variable 'Variable:0' shape=() dtype=string, numpy=b'This is a string'>

In [18]:
rank2_variable = tf.Variable([["hello", 'adf'], ['a', 'b']], tf.string)

In [19]:
rank2_variable.shape

TensorShape([2, 2])

In [20]:
t = tf.ones([1,2,3])

In [21]:
t

<tf.Tensor: shape=(1, 2, 3), dtype=float32, numpy=
array([[[1., 1., 1.],
        [1., 1., 1.]]], dtype=float32)>

In [22]:
t = tf.reshape(t, [3,2,1])

In [23]:
t

<tf.Tensor: shape=(3, 2, 1), dtype=float32, numpy=
array([[[1.],
        [1.]],

       [[1.],
        [1.]],

       [[1.],
        [1.]]], dtype=float32)>

In [27]:
t = tf.reshape(t, [3,-1])

In [28]:
t

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[1., 1.],
       [1., 1.],
       [1., 1.]], dtype=float32)>